HZ: 20.0
TARGET_VELOCITY: 0.3
MAX_VELOCITY: 0.4
MIN_VELOCITY: 0.0
MAX_OMEGA: 3.0
MAX_ACCELERATION: 0.8
MAX_ANG_ACCELERATION: 3.5
VELOCITY_RES: 0.025
OMEGA_RES: 0.025
SIM_TIME: 2.0
TO_GOAL_COST_GAIN: 1.0
SPEED_COST_GAIN: 0.5
OBSTACLE_COST_GAIN: 0.1
#ANGLE_RESOLUTION: 0.0087
#MAX_DIST: 10.0
GOAL_THRESHOLD: 0.3
#TURN_DIRECTION_THRESHOLD: 0.1
GOAL_X: 5.0
GOAL_Y: 5.0
